name: Build and Deploy Code

on: [push, pull_request]

jobs:
    job1:
       env:
          DATABASE_HOSTNAME: localhost
          DATABASE_PORT: 5432
          DATABASE_PASSWORD: "GA05niyu#"
          DATABASE_NAME :  Fastapi
          DATABASE_USERNAME: postgres
          SECRET_KEY: 917f15a68fca533d77fc6bf6d32e5022533eaa0c1f5147b267866b9a46a53c1c
          ALGORITHM: HS256
          ACCESS_TOKEN_EXPIRE_MINUTES: 30
       runs-on: ubuntu-latest
       steps:
          - name: pulling git repo
            uses: actions/checkout@v2
          - name: install python version 3.9
            uses: actions/setup-python@v2
            with: 
                python-version: "3.13.7"
          - name: update pip
            run: python -m pip install --upgrade pip
          - name: installing all dependencies
            run: pip install -r requirements.txt
          - name: test with pytest
            run: |
                pip install pytest
                pytest